/* 
    .SYNOPSIS
    | Install Warcraft III Tools
        
    .COPYRIGHT
    | (c)2010-2021 Griffon Studios
    
    .AUTHOR
    | Taylor Mouse
        
*/

/* Helpers */
fileIn "GriffonStudios_Warcraft_III_Tools\\GriffonStudios_Helpers.ms"
fileIn "GriffonStudios_Warcraft_III_Tools\\GriffonStudios_Warcraft_III_Helpers.ms"
fileIn "GriffonStudios_Warcraft_III_Tools\\GriffonStudios_AnimationWindow.ms"
fileIn "GriffonStudios_Warcraft_III_Tools\\GriffonStudios_Warcraft_III_UserPropertyEditor.ms"

/* Plugins */
fileIn "GriffonStudios_Warcraft_III_Tools\\GriffonStudios_Warcraft_III_Plugins_Attachment.ms"
fileIn "GriffonStudios_Warcraft_III_Tools\\GriffonStudios_Warcraft_III_Plugins_Behavior.ms"
fileIn "GriffonStudios_Warcraft_III_Tools\\GriffonStudios_Warcraft_III_Plugins_Event.ms"
fileIn "GriffonStudios_Warcraft_III_Tools\\GriffonStudios_Warcraft_III_Plugins_Material.ms"
fileIn "GriffonStudios_Warcraft_III_Tools\\GriffonStudios_Warcraft_III_Plugins_ParticleEmitter.ms"
fileIn "GriffonStudios_Warcraft_III_Tools\\GriffonStudios_Warcraft_III_Plugins_ParticleEmitter_v2.ms"
fileIn "GriffonStudios_Warcraft_III_Tools\\GriffonStudios_Warcraft_III_Plugins_Ribbon.ms"

/* Tools */
fileIn "GriffonStudios_Warcraft_III_Tools\\GriffonStudios_Warcraft_III_Import.ms"
fileIn "GriffonStudios_Warcraft_III_Tools\\GriffonStudios_Warcraft_III_Export.ms"
fileIn "GriffonStudios_Warcraft_III_Tools\\GriffonStudios_Warcraft_III_Macros.ms"
fileIn "GriffonStudios_Warcraft_III_Tools\\GriffonStudios_Warcraft_III_Tools_Dialog.ms"