gc()
struct mdx800 ( file, stream, seqs, glbs, mtls, texs, geos, geoa, txan, allObjects )
clearlistener()

mdx = mdx800()


Warcraft_III_Helpers.GetObjects mdx

Warcraft_III_Helpers.GetSEQS mdx
Warcraft_III_Helpers.GetMTLS mdx
Warcraft_III_Helpers.GetTEXS mdx
Warcraft_III_Helpers.GetGEOS mdx
Warcraft_III_Helpers.GetGEOA mdx
Warcraft_III_Helpers.GetGLBS mdx        
Warcraft_III_Helpers.GetTXAN mdx


mdx.TXAN.count

WC3_MDX.TXAN